### PR TITLE
Check that .pic urls are valid and embeddable before posting it (issue #43)

### LINKED ISSUE #43: Don't post broken images when using the .pic command
Right now when using the .pic command there is a decent chance that the image selected from google doesn't render in chat. Usually that is because
- The image link is broken (a 404)
- The host does not allow embedding and redirects to a full page
- The url isn't correctly rendered via plug because it contains characters that the plug image url doesn't recognize (e.g. "(")

In either case it renders a broken image link. We should check that the image can actually render for users before we post it into chat. Presumably just fetch the image url, check that the response is 200 and the content type looks like an image.

### PR DESCRIPTION
**Pull request by jkupferman**
Fixes #43

### CODE REVIEW

**Comment by jkupferman** [comment]
The second commit is for #37. Unfortunately they are in the same PR, but you can look at the commits separately.

**Comment by jkupferman** [comment]
Also happy birthday @joshlasdin !!!!

celebrate

File: bot/commands/imagesearch.js [hunk 1]
```diff
@@ -16,19 +16,31 @@ exports.init = function () {
 
             otterbot.log('Searching for an image: ' + message);
 
-            request(url, function (err, res, body) {
-                if (!err && res.statusCode == 200) {
-                    var images = JSON.parse(body)["responseData"]["results"];
+            var fetchImage = function(images) {
```
Comment (joshlasdin) [inline bot/commands/imagesearch.js]: @jkupferman Wondering if this would be more helpful abstracted out into a helper as we may have use for this elsewhere. Basically a function that would take a url, could return a `Promise` (don't have any of these elsewhere but I think it's a good fit for it), which would reject on error or non-200, and resolve with the url on success. Could then do the `chatSingle` in the resolve.

Let me know what you think, I could probably work through that this week if you dig it.

File: bot/commands/wiki.js [hunk 2]
```diff
@@ -13,10 +13,16 @@ exports.init = function () {
...
             easypedia(message, function (result) {
-                var sections = _.keys(result.text);
-
-                if (sections.length) {
-                    otterbot.chatSingle('From Wikipedia: ' + result.text[sections[0]][0].text);
+                var intro = result.text["Intro"];
+                if (intro && intro.length) {
+                    for (var i=0; i < intro.length; i++) {
+                        var line = intro[i].text;
+                        // skip any lines that look like wikipedia formatting (i.e. not text)
```
Comment (joshlasdin) [inline bot/commands/wiki.js]: :clap::clap::clap::clap::clap:

File: bot/commands/imagesearch.js (hunk 1 above)
Comment (jkupferman) [inline bot/commands/imagesearch.js]: In general I think having a "fetch this url and give me back a promise I can call .success and .error on" is useful.

In this particular instance there is a wrinkle with using a method like that because we also need to check the content type. That results in having the code change into something like....

```Javascript
request(url).success(function(headers) {
    if(_.contains(headers['content-type'], "image/")) {
         // this is actually the success case
    } else {
        // this is an error case (in the success block, ick)
    }
}).error(function() {
     // this is the main error case
})
```

Not sure, at least in this case, it's much better.

I'd say lets ship this and then we can add Helper.request() with all the promise magic and find the places to use it.

Comment (joshlasdin) [inline bot/commands/imagesearch.js]: Great idea!

Comment (joshlasdin) [inline bot/commands/imagesearch.js]: Dropped here, deploying now.

https://github.com/joshlasdin/otterbot/issues/45
